// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgS1IFlwXT5y87k9NI8Da8USGjqei8UE',
    appId: '1:875207782870:web:371ad8dd0dfc48cd6d7477',
    messagingSenderId: '875207782870',
    projectId: 'hypermarket-b59d9',
    authDomain: 'hypermarket-b59d9.firebaseapp.com',
    storageBucket: 'hypermarket-b59d9.firebasestorage.app',
    measurementId: 'G-REBT9NEQDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2vvRA5EDbrJjp9bCYCmktzp2RZEFb8i4',
    appId: '1:875207782870:android:9f118c1f3c7ed9476d7477',
    messagingSenderId: '875207782870',
    projectId: 'hypermarket-b59d9',
    storageBucket: 'hypermarket-b59d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9kVtMokUkty6SdXj36V28BEPi9Q4QDI',
    appId: '1:875207782870:ios:d5080bcc1d46ad766d7477',
    messagingSenderId: '875207782870',
    projectId: 'hypermarket-b59d9',
    storageBucket: 'hypermarket-b59d9.firebasestorage.app',
    iosBundleId: 'com.example.hyperMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9kVtMokUkty6SdXj36V28BEPi9Q4QDI',
    appId: '1:875207782870:ios:d5080bcc1d46ad766d7477',
    messagingSenderId: '875207782870',
    projectId: 'hypermarket-b59d9',
    storageBucket: 'hypermarket-b59d9.firebasestorage.app',
    iosBundleId: 'com.example.hyperMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkgS1IFlwXT5y87k9NI8Da8USGjqei8UE',
    appId: '1:875207782870:web:7f0a080b39ac464a6d7477',
    messagingSenderId: '875207782870',
    projectId: 'hypermarket-b59d9',
    authDomain: 'hypermarket-b59d9.firebaseapp.com',
    storageBucket: 'hypermarket-b59d9.firebasestorage.app',
    measurementId: 'G-R3JF44PSY7',
  );
}
